### PR TITLE
Redirect to EECS 485 GitHub tutorial

### PR DESCRIPTION
**Pull request by awdeorio**
Remove GitLab tutorial and replace with a redirect to the EECS 485 Version Control Tutorial.

The EECS 485 version control tutorial is a copy of the former EECS 280 tutorial, updated from GitLab to GitHub.

### Prerequisites
- [x] Merge EECS 485 PR https://github.com/eecs485staff/p1-insta485-static/pull/426 which adds a few changes for EECS 280 students, like downloading the EECS 280 `.gitignore`

### Validation
- Verify that the redirect works by clicking on the Git tutorial from the preview main page
- Read through the EECS 485 tutorial (after PR above is merged) and looks for EECS 485 things that might confuse an EECS 280 student.

### CODE REVIEW

**Review by ohjuny — APPROVED** [review]
LGTM.
Perhaps we could add a note in the 485 git tutorial for 280 students, mentioning things like "use a different name than p1-insta-static", etc.

**Comment by awdeorio** [comment]
> Perhaps we could add a note in the 485 git tutorial for 280 students, mentioning things like "use a different name than p1-insta-static", etc.

Like this at the top?  Or did you ahve something else in mind?  "We're assuming that you already have a folder, e.g., `p1-insta485-static/`.  Your folder name may be different.  It's OK if there aren't any files in it yet."

**Comment by ohjuny** [comment]
I guess we could just add one more example with a 280 project, so like:

"We're assuming that you already have a folder, e.g., p1-insta485-static/, p2-cv/. Your folder name may be different. It's OK if there aren't any files in it yet."

**Comment by awdeorio** [comment]
This is ready to go!

**Pull request merged**
