### PR TITLE
VS/WSL/VSCode tutorial nits and improvements.

### LINKED ISSUE #48: VS Code / WSL screenshot
It would nice to add a screenshot to the VS Code tutorial to accompany this pitfall:

> **Pitfall:** If you accidentally open VS Code from Windows mode, select "Reopen Folder in WSL".

Maybe something sort of like [this](https://ljr.im/articles/visual-studio-code-debugging-home-assistant-wsl-version/c5_p1_%E6%89%93%E5%BC%80%E6%9C%AC%E5%9C%B0%E7%9B%AE%E5%BD%95%E5%86%8D%E7%94%A8WSL%E9%87%8D%E6%96%B0%E5%8A%A0%E8%BD%BD.png)

Pro-tip: commit an unannotated screenshot first so we can play with the annotations if needed.

### PR DESCRIPTION
**Pull request by zjweiss**
Remove references to Windows/Linux in XCode tutorial, and Mac/Linux in VS tutorial.

Closes #48

### CODE REVIEW

**Comment by zjweiss** [comment]
@awdeorio, should be good for review now.

**Review by awdeorio — APPROVED** [review]
This looks great!  I made some edits.  Please double check me and confirm.  Then, I'll merge.

**Review by jamesjuett — APPROVED** [review]
Took a look and all LGTM.

**Comment by zjweiss** [comment]
LGTM.

**Pull request merged**
