### PR TITLE
Update setup_eecs281.md to include getopt instructions

### PR DESCRIPTION
**Pull request by zjweiss**
This commit adds instructions for using getopt to the eecs281 setup tutorial. Specifically, this commit does the following:

- Adds instructions for including getopt for Visual Studio.
- Provides access to getopt.c and getopt.h
- Provides the boilerplate getopt code for students to use in all eecs281 projects.
- Updates `setup_visualstudio.md` to inform students that they must follow the steps in the `setup_eecs281.md` tutorial
- Updates instructions for editing the Makefile

### CODE REVIEW

**Comment by awdeorio** [comment]
I'd like to push a few nits.  Do you mind giving access to me? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by zjweiss** [comment]
Hmm... I think you should already have access to push commits to this PR:

image

**Comment by awdeorio** [comment]
I'm gonna guess that the trouble is due to two branches with the same name.  Could you try another PR with a different branch name?  Like this:

```console
$ git fetch
$ git checkout eecs281-setup
$ git rebase
$ git checkout -b eecs281-setup-getopt
... make changes
```

**Comment by zjweiss** [comment]
Sorry for all the back and forth with getting this PR setup properly. I'm pretty sure that I named the new branch `eecs281-setup-getopt`, nevertheless, please try PR: https://github.com/eecs280staff/tutorials/pull/40

**Comment by seshrs** [comment]
@awdeorio looks like this PR is set from a fork, you'll need to add @zjweiss's forked repo as a new Git remote, fetch from the remote and checkexjout the branch from there...

**Comment by awdeorio** [comment]
@seshrs Looks like the problem is with the `gh` utility.  You can easily checkout the target of a PR from a fork like this:

```console
$ gh pr checkout 40
```

But you'll notice that `gh` doesn't connect the local branch to the fork's upstream:
```console
$ git branch -lvv eecs281-setup-getopt main
* eecs281-setup-getopt f0a8366 Empty test commit - checking GitHub write permis...
  main                 7de9a98 [origin/main] Merge pull request #31 from ...
```

I solved the problem by specifying the remote in my `git push` command:
```console
git push git@github.com:zjweiss/tutorials.git
```

I realize that I could add a zjweiss upstream if I wanted to which I bleive would be an alias for `git@github.com:zjweiss/tutorials.git`.

**Comment by seshrs** [comment]
Thanks @awdeorio for the detailed (and satisfying) explanation of what happened!

**Comment by awdeorio** [comment]
Replaced by #40

**Review by mlkmooeeeed — COMMENTED** [review]
zjweiss:eecs281-setup

**Comment by mlkmooeeeed** [comment]
zjweiss:eecs281-setup

**Pull request closed without merging**
