### PR TITLE
Specify Ubuntu version in WSL install instructions

### LINKED ISSUE #185: Specify Ubuntu Version in WSL Tutorial
When students install WSL using `wsl --install`, they may get different versions depending on *when* they perform the install.  We could make sure students get the same version with `wsl --install -d Ubuntu-24.04`.

For example, at the time of this writing (late August 2024), Ubuntu 22.02 is at end-of-life.  Ubuntu 24.04 is available in the Microsoft App Store, and it's recommended by the Microsoft WSL installations instructions, *but it isn't yet the default* with `wsl --install`.  I expect that this could change sometime soon, possibly even in the middle of our busy beginning-of-term "install season".

See related discussion [here](https://github.com/eecs280staff/tutorials/issues/184#issuecomment-2307685222)

### PR DESCRIPTION
**Pull request by awdeorio**
Closes #185

### CODE REVIEW

**Comment by jamesjuett** [comment]
I'm running through the setup on a few machines with 24.04 to make sure everything looks ok.

**Comment by jamesjuett** [comment]
Looks like the `-d` is unnecessary and just `wsl --install Ubuntu-24.04` will work. Made a change to that since it's simpler.

image

**Review by jamesjuett — APPROVED** [review]
Tried setup on a Windows 10 and Windows 11 machine. Everything seemed ok. Address Sanitizer seems fine. Confirmed VS Code installs ok and basic debugger functionality works.

**Comment by awdeorio** [comment]
I appreciate the thorough testing!

Tagging @melodell because EECS 485 references this tutorial.

**Pull request merged**
