### PR TITLE
Simplify CodeLLDB input redirection

### PR DESCRIPTION
**Pull request by awdeorio**
Use the simpler version of input redirection for the Code LLDB extension on macOS.

### Validation
Check if this works on a mac with CodeLLDB and EECS 280 Project 1 main.exe with input redirection.

### CODE REVIEW

**Comment by ohjuny** [comment]
I get error on the launch.json file that reads "Property stdio is not allowed."

I am still able to click Run on the debugger, but it seems to block when user input is required (does not use the stdio argument in launch.json).

**Comment by awdeorio** [comment]
> I get error on the launch.json file that reads "Property stdio is not allowed."

Just double-checking: are you using the CodeLLDB extension?

**Comment by ohjuny** [comment]
Yikes, I was not...
Just installed and tried it again - it works!

**Review by ohjuny — APPROVED** [review]
Tested and works on M1 Macbook Pro.
LGTM

**Comment by awdeorio** [comment]
If you made this mistake, imagine how many more students might do the same!  I added a pitfall, take a look 14cd9bead9bfeecba5419eedcdcac89f6a321102

Also added a link to the CodeLLDB stdio configuration docs.

**Review by ohjuny — APPROVED** [review]
LGTM 🍡

**Pull request merged**
