### PR TITLE
VSCode updates to address issues 135 and 138.

### LINKED ISSUE #135: Windows VSCode sanitizers instructions refer to CodeLLDB, which is specific to macOS
** What **
[The Sanitizers section of the VSCode setup tutorial](https://eecs280staff.github.io/tutorials/setup_vscode.html#sanitizers) refers to a CodeLLDB extension setting for all operating systems, but according to the [Extensions](https://eecs280staff.github.io/tutorials/setup_vscode.html#macos-1) section of the same tutorial, CodeLLDB is only to be installed for macOS.

** Where **
Hyperlinked above.

** Current language **
> Open Settings on VSCode (macOS: Code > Settings > Settings, Windows: File > Preferences > Settings). Search for “lldb: show disassembly” (without the quotes) and set the option to never. (See [ASAN error shows assembly code](https://eecs280staff.github.io/tutorials/setup_vscode.html#asan-error-shows-assembly-code) for an explanation.)

** Proposed **
Make the CodeLLDB setting change explicitly specific to macOS only.

### LINKED ISSUE #138: VSCode on Windows screenshots
The screenshots in the Windows part of the VSCode tutorial were taken on a macOS laptop.  In most places, that's fine because they are the same as you would see on Windows.  It's a problem in the [Windows/WSL create launch.json](https://eecs280staff.github.io/tutorials/setup_vscode.html#windowswsl-create-launchjson) section.  The screenshots show stuff like "lldb", which is just wrong.

### PR DESCRIPTION
**Pull request by amirkamil**
~~Screenshots collected via Parallels. However, Parallels on the Apple M architecture does not support WSL 2, so I have not been able to successfully test the configuration. We need someone with a Windows machine to test this before the PR is merged.~~

This PR does the following:
- Updates the `launch.json` screenshots for Windows to show gdb rather than lldb. Fixes #138.
- Moves the lldb-specific settings tweak for the address sanitizer to the macOS-specific section. Fixes #135.
- Updates the text and screenshot to show that standard output appears under "Terminal" rather than "Debug Console".
- Mentions that on Windows, VSCode may not prompt to select the debugger (it did not on both machines I tried).
- Adds a note on how to get to "Add Configuration" if the button doesn't show up (one machine I tested had the button, the other did not).

### CODE REVIEW

**Comment by amirkamil** [comment]
I remembered that I have access to a remote Windows machine, so I was able to test this out. It works for me.

**Review by ohjuny — APPROVED** [review]
LGTM 🐰

**Comment by jamesjuett** [comment]
Sorry... I changed too many screenshots... rolling back...

**Comment by jamesjuett** [comment]
Sorry... cleaning up my mess again. I didn't realize the same image was reused in BOTH the Mac and Windows sections.

**Review by jamesjuett — APPROVED** [review]

**Pull request merged**
