### PR TITLE
Visual Studio Nits

### PR DESCRIPTION
**Pull request by awdeorio**
Small changes to the Visual Studio tutorial suggested by @zjweiss in his comments on #44

### CODE REVIEW

**Comment by awdeorio** [comment]
@zjweiss could you elaborate on your earlier comment?  I don't have a windows machine so I'm not sure how to open the WSL preferences menu.  Just tell me and I'll add it!  Even better, take a screenshot and I'll add that!

> I also spent around ~15 minutes trying to figure out the copy/paste into Ubuntu WSL guide (https://devblogs.microsoft.com/commandline/copy-and-paste-arrives-for-linuxwsl-consoles/), but couldn't figure out how to open the WSL preferences menu.

**Comment by zjweiss** [comment]
Sounds good. I'll do some more digging around and figure out how to open the WSL preferences menu.

**Comment by zjweiss** [comment]
I'll be working on my changes in #50

**Comment by zjweiss** [comment]
I figured out the WSL Copy/Pate issue and put instructions for it in [b39d137](https://github.com/eecs280staff/tutorials/pull/50/commits/b39d13771dc06f63c1476bc95ace90258f6c806a) and [7ead0ba](https://github.com/eecs280staff/tutorials/pull/50/commits/7ead0baaf361bf6effe79d8c77b0a44b93f9b17c)

**Comment by awdeorio** [comment]
@zjweiss This PR includes your changes from #50 plus other changes I made in response to your comments.  Could you take a look?  Then, I'll merge.

**Comment by awdeorio** [comment]
I'm gonna merge this.  @zjweiss Please let me know if I screwed up any of your comments.

**Comment by zjweiss** [comment]
Sorry for the delay, but it all LGTM. I'm planning on taking a look at #6 later today.

**Pull request merged**
