### PR TITLE
Proposed Front Page

### PR DESCRIPTION
**Pull request by jamesjuett**
This PR is a proposal to use the existing "tutorials" section from eecs280.org as a front page for the tutorials. (And to remove it from the website as in https://github.com/eecs280staff/eecs280.org/pull/483.) I've made some modifications vs. what was on eecs280.org to decouple from the specifics of EECS 280 as a course (e.g. removed reference to tutorial practice in labs). 

I'll suggest this, at least as a starting point, since it's been through a few rounds of feedback from the F22 staff and has generally been helpful for students I've interacted with.

@ohjuny @zjweiss Would you mind taking a look at this and sharing any thoughts? I'm particularly interested in a student perspective, either yours or any insights you have into how to best organize things to be approachable to EECS 280 students in general.

The structure of the page encodes the recommended grouping and sequencing for the tutorials, especially in the setup sequence. It does add more content on the front page vs. a minimalistic approach (e.g. a simple link to each), but I think this is appropriate, especially given that the primary audience is students just coming out of CS 1 (e.g. many aren't going to know what an "Address Sanitizer" is.)

For context, here's also the original PR that introduced this on eecs280.org:
https://github.com/eecs280staff/eecs280.org/pull/449

### CODE REVIEW

**Comment by zjweiss** [comment]
I wasn't able to view the eecs280.org PRs, as I don't have access to that repo. But, as I understand it, you are planning on removing the tutorials section from the eecs280.org homepage (https://eecs280.org/#tutorials), and replacing it with a link to this new tutorials homepage. Is that the correct understanding?

Is this new page supposed to replace the current page hosted at: https://eecs280staff.github.io/tutorials/? If so, I think it may still be helpful to keep a text-based index of all the tutorials that 280 hosts (it may be more useful to students in courses beyond 280, who know what they are looking for.

I think that this new front page is good, and provides students with a welcoming way to approach looking at tutorials. I think that the way it is currently structured in your PR is good (and pretty similar to the way it currently is on the eecs280.org site).

Is there a particular reason you want to remove the existing "tutorials" sections? I don't see the harm in keeping this "front page" on its own page, as well as, having an identical copy on the eecs280.org homepage.

**Comment by ohjuny** [comment]
@zjweiss here is a side-by-side look at the current vs proposed layout:
side-by-side

In general, I am a huge fan of this "chunked" layout to make it less intimidating for students. Also agree that it looks cleaner without the 280-specific "includes practice in lab" icon. Building on @zjweiss 's answer, I also do not see a need to remove the "tutorials" section from the 280 homepage. I think it is useful for students to just be able to go to the 280 homepage to find all the tutorials there.

One small point is that I am not sure if the IDE icons were removed on purpose, but I think it looked better with the icons.

One bigger point is that the "Full Walkthrough - Start Here!" button could be confusing for some students. As a new student entering this page, they see a (1) big button that says "start here", but also (2) a numbered list of tutorials that starts with 1 just underneath it. Some way that makes it clear that the "Full Walkthrough" contains the 3 tutorials listed beneath it could be helpful.

In general, a big fan of this layout!

**Comment by awdeorio** [comment]
We may not need the "Start here" button anymore.  The only thing students really need to get started on Project 1 is a link to one of the IDE tutorials.  For example, take a look at how I've modified the P1 setup section: https://github.com/eecs280staff/p1-stats/pull/318 All it really does is link to the IDE tutorials.  Recall that the each IDE tutorial reminds the student to follow a CLI Tools Tutorial (macOS or WSL).

My thinking is that the primary audience for this page is a student who has already been through a tutorial and wants to refresh.  First-time visitors will probably be linked directly to a specific tutorial from a project spec.

**Comment by jamesjuett** [comment]
I agree with everyone that the "Start Here" button is not necessary. The only reason it's in there now is to avoid leaving `setup.md` orphaned. But, I also agree with the assessment that `setup.md` is probably not necessary. It just walks students through the 1. 2. 3. sequence that's already on this proposed main page.

I'm ok with leaving this content on eecs280.org, but @awdeorio has been working on the W23 site and I believe the intent is to remove it. I think that's reasonable if we're trying to slim down the main eecs280.org, but in that case I do think having it (or something) as front page for the tutorials makes sense.

**Comment by jamesjuett** [comment]
Ope, good catch @awdeorio on the duplicate `index.md`.

**Comment by awdeorio** [comment]
I fixed the custom icons and removed the "Start Here" button.  I also played around with adding a Quick Start (5bf3166c717b7209ebd83df0c46e5d98b5434ce2).

**Comment by seshrs** [comment]
(Sorry about the failing PR preview, I just pushed an update that generates PDFs. Debugging...)

**Comment by seshrs** [comment]
Figured out the issue with the PR previews! TIL exactly what `set +o pipefail` does. https://github.com/seshrs/build-primer-spec-action/commit/d5c74526928878549bdd1066b2177c3be0d1ec0c

**Comment by jamesjuett** [comment]
After some thought, I don't think a "straight to the IDE" quick start is a good idea.

Two points:
 - This structure sends new students to the IDE first, then bounces them back to CLI tools. It makes more sense to me to just start them at the CLI tools as step 1, then an IDE as step 2.
 - IMO this will encourage students to only work through the IDE tutorial (and the CLI tutorial, linked from there). But, both the makefile tutorial and the upcoming CLI tutorial (#41) should be a part of the initial sequence of tutorials that we recommend.

However, I do think it is helpful to think about the "shortest path" through the tutorials to a successful start to EECS 280, and what it would look like for most students in 280. (I don't think it's helpful to have anything at all that is a "shortest path" that an advanced students would take - they can figure out what to skip just fine.) In my opinion, that is:

1.1 Install CLI tools
1.2 CLI Tutorial (#41)
2 IDE Setup Tutorial
3 Makefiles (maybe? But I think yes given that we depend on them heavily in our project specs)
 
This would not include CAEN Linux. I moved this in 6e6ef86.

**Comment by awdeorio** [comment]
I'd like to get this merged ASAP because there's now a live link to it on eecs280.org.  I removed the controversial Quick Start 22b02804bd09484ec43157aa2a3ab12dd6c75469 and I'll move that discussion to a stand-alone PR.

I think this is good to go as-is and we can make additional improvements in separate PRs.

**Review by awdeorio — APPROVED** [review]

**Pull request merged**
