### PR TITLE
VS Code WSL Install Rework

### LINKED ISSUE #155: "Reopen Folder in WSL" no longer in Remote Menu
We used to tell students to click the little green button in the bottom left and select "Reopen Folder in WSL".

Unfortunately, it looks like that menu option was removed:
https://github.com/microsoft/vscode/issues/177093

Instead, "Reopen Folder in WSL" can be found via the command palette, ctrl+shift+p.

### PR DESCRIPTION
**Pull request by jamesjuett**
This PR does a few things:
- Removes some duplication in the prerequisites and install sections.
- Updates installation instructions to remove unnecessary computer reboot. Instead, add a note to `code .` pro-tip that restarting the shell may be required. (https://github.com/microsoft/vscode/issues/74116)
- Changes extension install to use VS Code UI
- Adds some context on WSL mode
- Fixes #155 
- Partial work towards #149

### CODE REVIEW

**Review by awdeorio — APPROVED** [review]
LGTM. I pushed a change to the WSL Mode pitfall callout.  Take a look at f6743064e9583f146cec81bc1414a4e95740d724

**Comment by jamesjuett** [comment]
> LGTM. I pushed a change to the WSL Mode pitfall callout. Take a look at [f674306](https://github.com/eecs280staff/tutorials/commit/f6743064e9583f146cec81bc1414a4e95740d724)

Thanks! Splitting it up is a good idea.

**Comment by jamesjuett** [comment]
Chatted with @amirkamil about this today. He's going to review and run through the new instructions before we merge.

**Review by amirkamil — APPROVED** [review]
Instructions worked for me.

**Pull request merged**
